name: Binder CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build and cache on mybinder.org
        uses: jupyterhub/repo2docker-action@master
        with:
          NO_PUSH: true
          MYBINDERORG_TAG: ${{ github.event.ref }}

      - name: Show link
        run: |
          echo "The binder link is: ${{ (github.event.pull_request_target || github.event.pull_request).head.repo.full_name }}/${{ (github.event.pull_request_target || github.event.pull_request).head.sha }})"
